name: Package and Push

on:
  # Triggers the workflow on pull request events and merges/pushes to main
  push:
    branches:
      - master
      - main

  pull_request:
    types: [opened, synchronize, reopened]

  schedule:
    # Daily 5am australian/brisbane time
    - cron: "0 19 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required to obtain the ID token from GitHub Actions
      contents: read # Required to check out code
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true # to allow setting version env var
      VERSION: "1.1.${{ github.run_number }}"
      OCTOPUS_SPACE: "Core Platform"
      
    steps:
      - name: Add nightly suffix if nightly
        if: github.event_name == 'schedule'
        run: |
          version="${{ env.VERSION }}-nightly-$(date +'%Y%m%d%H%M%S')"
          echo "Current Version: ${version}"
          echo "VERSION=${version}" >> "$GITHUB_ENV"

      - name: Add branch suffix if branch
        if: github.event_name == 'pull_request'
        run: |
          version=$(echo ${{ env.VERSION }}-${{ github.head_ref || github.ref }} | tr "/" "-")
          echo "Current Version: ${version}"
          echo "VERSION=${version}" >> "$GITHUB_ENV"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # all
          
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      # GeneratePackageOnBuild is specified in the csproj, so this will produce a nupkg
      - name: Pack
        run: dotnet publish -c Release /p:Version=${{ env.VERSION }} ./source

      - name: Login to Octopus Deploy ğŸ™
        if: (! contains(github.ref, '/merge')) && (! contains(github.ref, '/dependabot/')) && (! contains(github.ref, 'prettybot/'))
        uses: OctopusDeploy/login@v1
        with: 
          server: https://deploy.octopus.app
          service_account_id: 2552cea7-8cee-454e-a56b-e20e373e9c1f

      - name: Push to Octopus ğŸ™
        if: (! contains(github.ref, '/merge')) && (! contains(github.ref, '/dependabot/')) && (! contains(github.ref, 'prettybot/'))
        uses: OctopusDeploy/push-package-action@v3
        with:
          packages: ./source/bin/Release/octopus.dbup.sqlserver.${{ env.VERSION }}.nupkg

      - name: Create a release in Octopus Deploy ğŸ™
        if: (! contains(github.ref, '/merge')) && (! contains(github.ref, '/dependabot/')) && (! contains(github.ref, 'prettybot/'))
        uses: OctopusDeploy/create-release-action@v3
        with:
          project: "Octopus.Dbup.SqlServer"
          packages: |
            octopus.dbup.sqlserver: ${{ env.VERSION }}
